common/models/Ranking.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "ranking".
 *
 * @property integer $id
 * @property string $event_slug
 * @property string $course_slug
 * @property string $category_slug
 * @property string $event_title
 * @property string $course_title
 * @property string $category_title
 * @property integer $pnc
 * @property string $first_name
 * @property string $last_name
 * @property string $city
 * @property string $gender
 * @property string $final_time
 * @property integer $position_category
 * @property integer $position_course
 */
class Ranking extends \yii\db\ActiveRecord
{
    const TIME_DNS = 'DNS'; //Did not start
    const TIME_DSC = 'DSC'; //Desqualified
    const TIME_ABD = 'ABD'; //Abandoned
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ranking';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event_slug', 'course_slug', 'category_slug', 'event_title', 'course_title', 'category_title', 'pnc', 'first_name', 'last_name', 'position_category', 'sex', 'city', 'final_time'], 'required'],
            [['pnc', 'position_category', 'position_course'], 'integer'],
            [['event_slug', 'course_slug', 'category_slug', 'event_title', 'course_title', 'category_title', 'first_name', 'last_name', 'city'], 'string', 'max' => 255],
            [['pnc'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'event_slug' => 'Event Slug',
            'course_slug' => 'Course Slug',
            'category_slug' => 'Category Slug',
            'event_title' => 'Eveniment',
            'course_title' => 'Traseu',
            'category_title' => 'Categorie',
            'pnc' => 'CNP',
            'first_name' => 'Prenume',
            'last_name' => 'Nume',
            'position_category' => 'Pozitia',
            'position_course' => 'Position Course',
        ];
    }

    /**
     * @inheritdoc
     * @return RankingQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new RankingQuery(get_called_class());
    }
    
    public function getTime()
    {
        switch (strtoupper($this->final_time)) {
            case self::TIME_DNS:
                return 'Nu a luat startul';
                break;
            case self::TIME_DSC:
                return 'Descalificat';
                break;
            case self::TIME_ABD:
                return 'Abandon';
                break;
            default:                
                return $this->final_time;
                break;
        }
        
    }
    public function getFullname()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

backend/controllers/RankingController.php
<?php

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\Ranking;
use common\models\Event;
use common\models\RankingSearch;
use backend\models\ImportRankingsForm;
use yii\web\UploadedFile;

class RankingController extends Controller
{
    
    public function behaviors()
    {
        return [            
            'access' => [                
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
    
    public function actionIndex()
    {
        $searchModel = new RankingSearch();
		$searchModel->event_slug = Event::findOne(['year(start_date)' => date('Y')])->slug;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);        
    }
    
    public function actionImport()
    {
        $model = new ImportRankingsForm();
       
        if (Yii::$app->request->isPost) {

            $csvFile = UploadedFile::getInstance($model, 'file');
            $extension = strtolower(pathinfo($csvFile->name, PATHINFO_EXTENSION));
            $model->file = $csvFile;
            $model->event = Yii::$app->request->post('ImportRankingsForm')['event'];
            
            if ($model->validate()) { 
                $count = $this->importCsv($csvFile->tempName, $model->event);
                
                if ($count) {
                    Yii::$app->session->setFlash('success', $count . ' rezultate au fost importate');
                } else {
                    Yii::$app->session->setFlash('error', 'Nici un rezultat nu a fost importat');
                }

                return $this->redirect(['index']);
            }
        }

        return $this->renderAjax('import', ['model' => $model]);
    }
    
    private function importCsv($file, $event_slug)
    {
        $items = array();
        $attributes = array();
        $row = 1;
        
        if (($handle = fopen($file, "r")) === false) {
            return false;
        }
        
        while (($data = fgetcsv($handle, 1000, ';', '"')) !== false) {
            $num = count($data);
            $item = array();
            
            //echo "<p> $num fields in line $row: <br /></p>\n";
            if ($row === 1) {
                for ($c = 0; $c < $num; $c++) {
                    $attributes []= $data[$c];
                }
            } else {  
                for ($c = 0; $c < $num; $c++) {
                    //echo $data[$c] . "<br />\n";
                    $item []= $data[$c];
                }
            }
            
            $row++;
            if ($item !== array()) {
                $items []= $item;
            }
        }
            
//        echo 'attributes\n';
//        var_dump($attributes);die;
//        echo 'items\n';
//        var_dump($items);die;
        
        if ($items === array()) {
            return false;
        }
        
        return Yii::$app->db->createCommand()->batchInsert(Ranking::tableName(), $attributes, $items)->execute();

  
    }
    
    public function actionReset()
    {
        if (!Yii::$app->request->isPost)
        {
            throw new \yii\web\BadRequestHttpException;
        }
        
        $event = Event::findBySlug(Yii::$app->request->post('event'));
        
        $deleted = Ranking::deleteAll('event_slug=:event', [':event' => $event->slug]);
        if ($deleted > 0) {
            Yii::$app->session->setFlash('success', $deleted . ' records were deleted from Ranking table for event ' . $event->slug);
        } else {
            Yii::$app->session->setFlash('error', 'No records deleted from Ranking table for event '. $event->slug); 
        }
        
        return $this->redirect(['index']);
    }

}

backend/views/ranking/import.php
<?php

use yii\bootstrap\ActiveForm;

use yii\helpers\Html;

$eventsList = ['MBR2019' => 'Mamut Bike Race 2019', 'JBR2019' => 'Junior Bike Race 2019'];
?>

<div class="event-form">
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'id' => 'importCsvForm']]) ?>
    
    <?= $form->field($model, 'event')->dropDownList($eventsList) ?>
    <?= $form->field($model, 'file')->fileInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Importa rezultatele', ['class' => 'btn btn-success']) ?>
    </div>

<?php ActiveForm::end() ?>  
</div>

backend/views/ranking/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\helpers\ArrayHelper;
use common\models\Event;
use common\models\Ranking;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RankingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Clasamente';
$this->params['breadcrumbs'][] = $this->title;

$events = ArrayHelper::map(Event::find()->all(), 'slug', 'title');
$distinctArray = Ranking::find()->distinct(true)->all();  
$courses = ArrayHelper::map($distinctArray, 'course_slug', 'course_title');
$categories = ArrayHelper::map($distinctArray, 'category_slug', 'category_title');

?>
<div class="event-index">

    <h1><?= Html::encode($this->title) ?></h1>
    
<?php if (Yii::$app->session->getFlash('success')): ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo Yii::$app->session->getFlash('success') ?>
    </div>
<?php endif; ?>

<?php if (Yii::$app->session->getFlash('error')): ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo Yii::$app->session->getFlash('error') ?>
    </div>
<?php endif; ?>
    
    <div class="toolbar"style="margin:10px 0;">
        <?= Html::button('Importa rezultate', [
            'value' => Url::to(['ranking/import']),
            'id' => 'importRankingsBtn',
            'class' => 'btn btn-success btn-primary']) ?>
		<?php foreach (Event::find()->all() as $event) : ?>
		
		<?= Html::button("Sterge rezultate {$event->slug}", [
            'data-url' => Url::to(['ranking/reset']),
            'data-event' => $event->slug,
			'disabled' => date('Y', strtotime($event->start_date)) < date('Y') ? true : false,
            'id' => 'deleteRankings'.$event->slug,
            'data-confirmation' => "Esti sigur ca vrei sa stergi toate rezultatele de la {$event->slug}?",
            'class' => "btn btn-danger deleteRankingsBtn"]) ?>
		<?php endforeach; ?>       
    </div>
    
    <?php 
 Modal::begin([
     'header' => 'Import rezultate',
     'id' => 'modalImport',
 ]);
 
 echo '<div id="modalContent"></div>';
 Modal::end();
    ?>
    
    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'event_slug',
                'value' => 'event_title',
                'filter' => $events,
                'label' => 'Eveniment'
            ], 
            [
                'attribute' => 'course_slug',
                'value' => 'course_title',
                'filter' => $courses,
                'label' => 'Traseu'
            ], 
            [
                'attribute' => 'category_slug',
                'value' => 'category_title',
                'filter' => $categories,
                'label' => 'Categorie'
            ], 
            'first_name', 
            'last_name', 
            'team', 
            'position_category',
            [
                'attribute' => 'final_time',
                'value' => 'time',
                'label' => 'Timp'
            ],
        ],
    ]); ?>

</div>