jbr/controllers/SiteController.php
<?php
namespace jbr\controllers;

use Yii;
use jbr\models\ContactForm;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use jbr\models\SubscriberSearchWeb;
use common\models\Subscriber;
use common\models\Ranking;
use common\models\RankingSearch;

use common\models\Course;
use common\models\Category;
use common\models\Event;
use yii\helpers\ArrayHelper;

use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	
	public function actionOffline()
	{
		$this->layout = 'maintenance';
		return $this->render('offline');
	}
	
	public function actionError()
	{
		$exception = Yii::$app->errorHandler->exception;
		if ($exception !== null) {
			return $this->render('error', ['exception' => $exception]);
		}
	}

	public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['jbrContactEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionTrack()
    {
        $year = Yii::$app->params['currentEventYear'];
    
        $eventSlug = Event::getEventSlugFromParams($year);
    
        $categories = Category::find()
            ->joinWith('course')
            ->join('INNER JOIN', 'event', 'event.id = course.event_id')
            ->where('event.slug=:event', [':event' => $eventSlug])
            ->orderBy('category.id ASC')
            ->all();
        
        return $this->render('track', ['categories' => $categories]);
    }
    
    public function actionRiders()
    {
		$this->view->title = "Participanți";
		
		$request = Yii::$app->request;
		$year = $request->get('year');
					
		if (!$year) {
			$year = Yii::$app->params['currentEventYear'];
		} else {
			$this->view->title = "Participanți, {$year}";
			$qp = Yii::$app->request->queryParams;
			$qp['year'] = $year;
			Yii::$app->request->setQueryParams($qp);
		}
		
		$eventSlug = Event::getEventSlugFromParams($year);
		
        $searchModel = new SubscriberSearchWeb();		
		
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        $courses = ArrayHelper::map(
            Course::find()
                ->joinWith('event')
                ->where('event.slug=:event', [':event' => $eventSlug])
                ->all(), 
            'title', 'title');
        
        $categories = ArrayHelper::map(
            Category::find()
                ->joinWith('course')
                ->join('INNER JOIN', 'event', 'event.id = course.event_id')
                ->where('event.slug=:event', [':event' => $eventSlug])
                ->orderBy('category.id ASC')
                ->all(), 
            'title', 'title', 'course.title');

        return $this->render('riders', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'courses' => $courses,
            'categories' => $categories,
            'statistics' => $searchModel->getStatistics(),
        ]);
    }
    
    public function actionRegulation()
    {
        $year = Yii::$app->params['currentEventYear'];
    
        $eventSlug = Event::getEventSlugFromParams($year);
        
        $categories = Category::find()
                ->joinWith('course')
                ->join('INNER JOIN', 'event', 'event.id = course.event_id')
                ->where('event.slug=:event', [':event' => $eventSlug])
                ->orderBy('category.id ASC')
                ->all();
        
        return $this->render('regulation',
            [
                'categories' => $categories
            ]
        );
    }
    
	public function actionCheckcnp($cnp)
	{		
		$model = Subscriber::findBySql("select * from subscriber where pnc=:cnp", [':cnp' => $cnp])->one();
		
		$return = null;
		if ($model) {
			$return = array(
				'first_name' => $model->first_name,
				'last_name' => $model->last_name,
				'pnc' => $model->pnc,
				'email' => $model->email,
				'phone' => $model->phone,
				'city' => $model->city,
			);					
		}
		
		echo \yii\helpers\Json::encode($return);
	}
	
    public function actionRegister()
    {
        $model = new Subscriber();
        $model->setScenario('WebsubscribeJbr');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('registered', true);
            return $this->redirect(['riders']);
        } else {
            return $this->render('register', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionDeclaratie()
    {
        $filePath = Yii::getAlias('@files') . DIRECTORY_SEPARATOR . 'jbr-declaratie-tutore.pdf';
        if (file_exists($filePath)) {
            Yii::$app->response->sendFile($filePath, 'jbr-declaratie-tutore.pdf');
        } else {
            return $this->goHome();
        }                    
    }
    
    public function actionSchedule()
    {
        return $this->render('schedule');
    }
    
    public function actionMaps()
    {
        return $this->render('maps');
    }
    
    public function actionRankings()
    {
		$request = Yii::$app->request;
		$year = $request->get('year');
		
		if (!$year) {
			$year = Yii::$app->params['currentEventYear'];
		}
				
		if (!ArrayHelper::keyExists("{$year}", Yii::$app->params['events'])) {
			throw new NotFoundHttpException("Clasamentul nu exista.");
		}
		
		$eventSlug = Event::getEventSlugFromParams($year);
		//Yii::error($eventSlug);
		
		$eventCategories = array();
		if (ArrayHelper::keyExists("categories", Yii::$app->params['events'][$year])) {
			$eventCategories = ArrayHelper::getValue(Yii::$app->params, "events.{$year}.categories");			
		} else {
			$eventCategories = Category::getCategoriesSlugTitle($eventSlug, true, false);	
		}
		//Yii::error($eventCategories);
		
        $count = Ranking::find()->andWhere('event_slug=:event', [':event' => $eventSlug])->count();
		
        $searchModel = new RankingSearch();
        $dataproviders = array();
        
        foreach ($eventCategories as $category => $categoryDescription) {
             $dp = $this->getDataProviderFor($eventSlug, $category, $searchModel);
             if ($dp) {
                 $dataproviders [$category]= $dp;
             }                  
        }
		
        $this->view->title = "Clasamente Junior Bike Race, {$year}";
		
        return $this->render('rankings', [
            'isRanking' => $count > 0,
            'dataproviders' => $dataproviders,
			'event' => $eventSlug,
			'categories' => $eventCategories,
        ]);
    }		
    
    private function getDataProviderFor($event, $category, $searchModel)
    {
        $dataProvider = $searchModel->search([
            'RankingSearch' => [
                'event_slug' => $event,
                'category_slug' => $category,
            ]
        ]);
        
        if ($dataProvider->getTotalCount() > 0) {
            $dataProvider->sort = false;
            return $dataProvider;
        } 
        
        return false;
    }
}

jbr/views/layouts/_analytics.php
<?php

/**
 * Description of _analytics
 *
 * @author  Claudiu Crisan <claudiu.crisan at gmail.com>
 * @copyright (c) 
 * @date  May 8, 2015
 * @encoding UTF-8 
 */
?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55547197-2', 'auto');
  ga('send', 'pageview');

</script>

jbr/views/layouts/_breadcrumbs.php
<?php

/**
 * Description of _breadcrumbs
 *
 * @author  Claudiu Crisan <claudiu.crisan at gmail.com>
 * @copyright (c) 
 * @date  Apr 20, 2015
 * @encoding UTF-8 
 */
use yii\widgets\Breadcrumbs;

$links = [];
if (isset($this->params['breadcrumbs'])) {
    $links = $this->params['breadcrumbs'];
}
//var_dump($links);
?>

<!-- Start Outter Wrapper -->
<div class="outter-wrapper breadcrumb-wrapper">		

    <?=
    Breadcrumbs::widget([
        'tag' => 'div',
        'options' => [
            'class' => 'wrapper'
        ],
        'itemTemplate' => "{link}\n",
        'activeItemTemplate' => "{link}\n",
        'homeLink' => [
            'label' => 'Acasa', 
            'url' => Yii::$app->homeUrl, 
            'template' => '<span class="fa">&#xf015;</span> {link} / '
        ],
        'links' => $links,
    ])
    ?>
    <!--div class="wrapper">
        <a href="index.html" class="fa">&#xf015;</a> <a href="index.html">Home</a>
    </div-->
</div>

jbr/views/layouts/_footerContent.php
<?php
/**
 * Description of _footerContent
 *
 * @author  Claudiu Crisan <claudiu.crisan at gmail.com>
 * @copyright (c) 
 * @date  Apr 20, 2015
 * @encoding UTF-8 
 */
use yii\helpers\Url;

?>
<!-- Start Outter Wrapper -->
<div class="outter-wrapper footer-wrapper">		
    <div class="wrapper clearfix">
        <!-- Start Widget -->
        <div class="col-1-4 widget">
            <h3 class="widget-title">Organizator:</h3>
            <a class="logo" href="http://bicheru-cycling.ro" target="_blank">
                <img src="img/logo-bicheru.png" alt="Bicheru Cycling" />
            </a>	
        </div>

        <!-- Start Widget -->
        <div class="col-1-4 widget">
            <h3 class="widget-title">Partener:</h3>
            <a class="logo" href="http://primariaciugud.ro" target="_blank">
                <img style="margin-top: -30px;" src="img/logo-primaria-ciugud.png" alt="Primăria Ciugud, Alba" />
            </a>	
        </div>


        <!-- Start Widget -->
        <div class="col-1-4 widget">
            <h3 class="widget-title">Info</h3>
            <ul class="open-hours">
                <li>Data <span><?= Yii::$app->params['jbrCurrentEventDateTime'] ?></span></li>
                <li>Locația <span><?= Yii::$app->params['jbrCurrentLocation'] ?></span></li>
                <!--li>Contact <span><?= Yii::$app->params['jbrContactEmail'] ?></span></li-->
                <li>Descarcă<br/><strong><a href="<?= yii\helpers\Url::to(['site/declaratie']) ?>"><i class="fa fa-file-pdf-o">&nbsp;</i>Declarația pe proprie răspundere</a></strong></li>
            </ul>	
        </div>
		
        <!-- Start Widget -->
        <div class="col-1-4 widget last">
            <h3 class="widget-title">Arhiva JBR</h3>
            <ul class="open-hours">
                <li><a href="<?= Url::to(['site/rankings', 'year' => '2017']) ?>">2017 - Clasament</a>
				<li><a href="<?= Url::to(['site/rankings', 'year' => '2016']) ?>">2016 - Clasament</a>
				<li><a href="<?= Url::to(['site/rankings', 'year' => '2015']) ?>">2015 - Clasament</a>
            </ul>
        </div>

    </div>
</div>

jbr/views/layouts/_footerCopyright.php
<?php
/**
 * Description of _footerCopyright
 *
 * @author  Claudiu Crisan <claudiu.crisan at gmail.com>
 * @copyright (c) 
 * @date  Apr 20, 2015
 * @encoding UTF-8 
 */
?>
<!-- Start Outter Wrapper -->
<div class="outter-wrapper base-wrapper" id="copy">
    <div class="wrapper clearfix">
        <div class="left">&copy; Asociația Bicheru Cycling.</div>

        <!-- Social Icons -->
        <ul class="social-links right">
            <li><a class="fa" title="Facebook" href="https://www.facebook.com/juniorbikerace">&#xf09a;</a></li>
        </ul>
    </div>
</div>

jbr/views/layouts/_headerArea.php
<?php
/**
 * Description of _headerArea
 *
 * @author  Claudiu Crisan <claudiu.crisan at gmail.com>
 * @copyright (c) 
 * @date  Apr 20, 2015
 * @encoding UTF-8 
 */
?>
<!-- Header Area -->
<div class="outter-wrapper header-area header-style-3">
    <div class="wrapper clearfix logo-container">
        <header>
            <div class="clearfix">

                <!-- Start Logo -->
                <a class="logo centered" href="<?= Yii::$app->homeUrl ?>">
                    <img src="img/logo-jbr.png" alt="Junior Bike Race" />
                </a>

            </div>
        </header>
    </div>
</div>

jbr/views/layouts/_navArea.php
<?php
/**
 * Description of _navArea
 *
 * @author  Claudiu Crisan <claudiu.crisan at gmail.com>
 * @copyright (c) 
 * @date  Apr 20, 2015
 * @encoding UTF-8 
 */
use yii\helpers\Url;

?>
<!-- Post Header Area -->
<div class="outter-wrapper nav-container post-header-area header-style-3">

    <!-- Start Mobile Menu Icon -->
    <div id="mobile-header" class="">
        <a id="responsive-menu-button" href="#sidr-main">
            <em class="fa fa-bars"></em> Meniu
        </a>
    </div>

    <div id="navigation" class="clearfix">

        <div class="post-header-center centered-menu">
            
            <nav class="nav megamenu_container wrapper">
                <ul id="nav" class="centered-menu megamenu">
                    <?php if (common\models\Subscriber::isEventDay()) : ?>    
                        <li><a href="<?= Url::to(['site/rankings']) ?>">Clasament</a></li>
                    <?php else : ?>
                        <li><a href="<?= Url::to(['site/register']) ?>">ÎNSCRIERE</a></li>
                        <li><a href="<?= Url::to(['site/riders']) ?>">Participanți</a></li>
                    <?php endif; ?>
                    <li><a href="<?= Url::to(['site/schedule']) ?>">Program</a></li>
                    <li><a href="<?= Url::to(['site/about']) ?>">Despre JBR</a></li>
                    <li><a href="<?= Url::to(['site/track']) ?>">Traseu</a></li>
                    <li><a href="<?= Url::to(['site/maps']) ?>">Cum ajung?</a></li>
                    <li><a href="<?= Url::to(['site/regulation']) ?>">Regulament</a></li>
                </ul>
            </nav>            

        </div>

    </div>
</div>

jbr/views/layouts/_preHeaderArea.php
<?php
/**
 * Description of _preHeaderArea
 *
 * @author  Claudiu Crisan <claudiu.crisan at gmail.com>
 * @copyright (c) 
 * @date  Apr 20, 2015
 * @encoding UTF-8 
 */
?>
<!-- Pre Header Area -->
<div class="outter-wrapper pre-header-area header-style-3">
    <div class="wrapper clearfix">

        <div class="pre-header-left left">
            <!-- Second Nav -->
            <ul>
                <li><a class="fa fa-home" title="Junior Bike Race" href="<?= Yii::$app->homeUrl ?>">&nbsp;</a></li>
                <li><a class="fa" title="Facebook" href="https://www.facebook.com/juniorbikerace" target="_blank">&#xf09a;</a></li>
            </ul>
        </div>
        
        <?php if (!common\models\Subscriber::isEventDay()) : ?> 
        <div class="pre-header-right right">
            <strong>Au mai rămas:</strong> <div class="countdown styled"></div> 
        </div>				
        <?php endif ?>
    </div>	
</div> 

jbr/views/layouts/main.php
<?php

use yii\helpers\Html;
use app\assets\JbrAppAsset;
JbrAppAsset::register($this);

/* @var $this yii\web\View */
/* @var $content string */

?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?= Yii::$app->language ?>"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <meta content="black" name="apple-mobile-web-app-status-bar-style">

        <!-- Page title + Description -->
        <?php if (!empty($this->title)) : ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php else: ?>
        <title>Junior Bike Race</title>
        <?php endif; ?>
        <meta name="description" content="Junior Bike Race, Ciugud, Alba">

        <!-- Favicons -->
        <link rel="apple-touch-icon" sizes="57x57" href="favicons/apple-touch-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="114x114" href="favicons/apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="72x72" href="favicons/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="144x144" href="favicons/apple-touch-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="60x60" href="favicons/apple-touch-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="120x120" href="favicons/apple-touch-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="76x76" href="favicons/apple-touch-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="152x152" href="favicons/apple-touch-icon-152x152.png">
        <link rel="icon" type="image/png" href="favicons/favicon-196x196.png" sizes="196x196">
        <link rel="icon" type="image/png" href="favicons/favicon-160x160.png" sizes="160x160">
        <link rel="icon" type="image/png" href="favicons/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="favicons/favicon-16x16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="favicons/favicon-32x32.png" sizes="32x32">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="favicons/mstile-144x144.png">
        
        <link href='http://fonts.googleapis.com/css?family=Alegreya+SC:400,900|Roboto:400,700,900,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <?php $this->head() ?>    
    </head>
    <body>
        <?= $this->render('_analytics'); ?>
        
        <?php $this->beginBody() ?>
        
        <?= $this->render('_preHeaderArea'); ?>
        <?= $this->render('_headerArea'); ?>
        <?= $this->render('_navArea'); ?>


        <?= $content ?>


        <?= $this->render('_breadcrumbs'); ?>
        <?= $this->render('_footerContent'); ?>
        <?= $this->render('_footerCopyright'); ?>

        <?php $this->endBody()  ?>

    </body>
</html>


<?php $this->endPage() ?>

jbr/views/layouts/maintenance.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\JbrAppAsset;

JbrAppAsset::register($this);

/* @var $this yii\web\View */
/* @var $content string */
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?= Yii::$app->language ?>"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <meta content="black" name="apple-mobile-web-app-status-bar-style">

        <!-- Page title + Description -->
        <title>Junior Bike Race, by Bicheru-Cycling</title>
        <meta name="description" content="Junior Bike Race, concurs de ciclism destinat copiilor">

        <!-- Favicons -->
        <link rel="apple-touch-icon" sizes="57x57" href="/favicons/apple-touch-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/favicons/apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/favicons/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/favicons/apple-touch-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/favicons/apple-touch-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/favicons/apple-touch-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/favicons/apple-touch-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/favicons/apple-touch-icon-152x152.png">
        <link rel="icon" type="image/png" href="/favicons/favicon-196x196.png" sizes="196x196">
        <link rel="icon" type="image/png" href="/favicons/favicon-160x160.png" sizes="160x160">
        <link rel="icon" type="image/png" href="/favicons/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="/favicons/favicon-16x16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="/favicons/favicon-32x32.png" sizes="32x32">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/favicons/mstile-144x144.png">

        <link href='http://fonts.googleapis.com/css?family=Alegreya+SC:400,900|Roboto:400,700,900,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<?php $this->head() ?>    
    </head>
    <body>
		<?= $this->render('_analytics'); ?>

		<?php $this->beginBody() ?>

		<!-- Pre Header Area -->
		<div class="outter-wrapper pre-header-area header-style-3">
			<div class="wrapper clearfix">

				<div class="pre-header-left left">
					<!-- Second Nav -->
					<ul>
						<li><a class="fa fa-home" title="Junior Bike Race" href="<?= Yii::$app->homeUrl ?>">&nbsp;</a></li>
						<li><a class="fa" title="Facebook" href="https://www.facebook.com/juniorbikerace" target="_blank">&#xf09a;</a></li>
					</ul>
				</div>

			</div>	
		</div> 
		
		<?= $this->render('_headerArea'); ?>

		<div class="outter-wrapper footer-wrapper">		
			<div class="col-1-1 widget">&nbsp;</div>
		</div>
		
		<?= $content ?>

		<?= $this->render('_footerCopyright'); ?>

		<?php $this->endBody() ?>

    </body>
</html>


<?php $this->endPage() ?>