backend/controllers/SubscriberController.php
<?php

namespace backend\controllers;

use Yii;
use yii\base\Model;
use yii\filters\AccessControl;
use common\models\Subscriber;
use backend\models\SubscriberSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\Event;
/**
 * SubscriberController implements the CRUD actions for Subscriber model.
 */
class SubscriberController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [                
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Subscriber models.
     * @return mixed
     */
    public function actionIndex()
    {
	    $searchModel = new SubscriberSearch();
		$sql = "select * from event WHERE start_date > now() order by start_date asc limit 1";
		$event = Event::findBySql($sql, [])->one();
		if ($event) {
			$searchModel->event = $event->slug;
		}
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * Lists all Subscriber models.
     * @return mixed
     */
    public function actionPaylist()
    {
        $searchModel = new SubscriberSearch();
        $sql = "select * from event order by id desc";
        $event = Event::findBySql($sql, [])->one();
        if ($event) {
            $searchModel->event = $event->slug;
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->setPageSize(100);
        
        return $this->render('paylist', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionBulkpay()
    {
        $suma = Yii::$app->request->post('suma', 0);
        $suma = (int) $suma;
        
        $data = Yii::$app->request->post('data', date('Y-m-d'));
        if (!isset($data) || empty($data)) {
            $data = date('Y-m-d');
        }
        $data = date('Y-m-d', strtotime($data));
        
        $descriere = Yii::$app->request->post('descriere');
        if (!($suma > 0) && empty($descriere)) {
            $descriere = "GRATUIT";
        }
        
        $selection = (array)Yii::$app->request->post('selection');
        $updated = array();
        foreach ($selection as $id) {
            $subscriber = Subscriber::findOne((int) $id);
            if (!$subscriber) continue;
            $subscriber->payed = 1;
            $subscriber->amount_payed = $suma;
            $subscriber->payment_date = $data;
            $subscriber->payment_description = $descriere;
            if (!$subscriber->validate()) continue;
            if ($subscriber->save(false)) {
                $updated []= $subscriber->id;
            }
        }
        $count = count($updated);
        $ids = implode(',', $updated);
        Yii::$app->session->setFlash('success', "Ai marcat plata de {$suma} pentru {$count} participanti. IDs: {$ids}");
        
        $this->redirect(['subscriber/paylist']);
    }

    /**
     * Displays a single Subscriber model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Subscriber model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Subscriber();
		$model->payed = Subscriber::NOT_PAYED;
		$model->email_sent = '0';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
            //return $this->redirect(['view', 'id' => $model->id]);
        } else {
			$categories = \common\models\Category::getCategoriesListItems();
            return $this->render('create', [
                'model' => $model, 'categories' => $categories
            ]);
        }
    }

    /**
     * Updates an existing Subscriber model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
            //return $this->redirect(['view', 'id' => $model->id]);
        } else {
			$event = $model->category->course->event->slug;
			$categories = \common\models\Category::getCategoriesListItems($event);

            return $this->render('update', [
                'model' => $model, 'categories' => $categories
            ]);
        }
    }

    /**
     * Deletes an existing Subscriber model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
//    public function actionDownload()
//    {
//        $searchModel = new SubscriberSearch();
//        $data = $searchModel->getForCsv();
//
//    }
    
    /**
     * Finds the Subscriber model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Subscriber the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Subscriber::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionDownload()
    {
        $event = Yii::$app->request->get('event', 'MBR2019');

        $sql = "select s.id as id_mbr, '' as 'nr_concurs',
            s.last_name as nume, s.first_name as prenume, t.title as traseu,
                    c.title as categorie,
                    s.pnc as cnp, s.gender as sex, s.city as localitate, s.phone as telefon,
                    IF((s.payed=1 and s.payment_date<=:dam_tricou), s.tshirt_size, '-') as tricou,
                    s.payed as platit, s.payment_date as data_platii, s.created_at as data_inscrierii
                    FROM
                    subscriber s INNER JOIN category c on c.id=s.category_id
                    inner join course t on t.id=c.course_id
                    inner join event e on e.id=t.event_id
                    where e.slug=:event_slug
                    order by t.title, s.id";
        
        $damTricou = date('Y-m-d', Yii::$app->params['damTricou']);
        
        $data = \Yii::$app->db->createCommand($sql, array(":event_slug" => $event, ":dam_tricou" => $damTricou))->queryAll();
        if (!empty($data)) {
            $file = tmpfile();
            $addHeader = true;
            foreach ($data as $row) {
                if ($addHeader) {
                    fputcsv($file, array_keys($row), ';');
                    $addHeader = false;
                }
                fputcsv($file, array_values($row), ';');
            }
            
            $filename = "inscrisi_{$event}_".date('Y-m-d'). ".csv";
            header('Pragma: public');
            header('Expires: 0');
            header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
            header("Content-type: application/csv; charset=UTF-8");
            header("Content-Disposition: attachment; filename={$filename}");
    
            rewind($file);
            while (!feof($file)) {
                echo fread($file, 1000);
            }
    
            fclose($file);
            Yii::$app->end();
        } else {
            echo "Nu s-au gasit rezultate. Nu am ce sa export.";
            Yii::$app->end();
        }
    }

    public function actionPrint($id)
    {
        $model = $this->findModel($id);
        $model->printDeclaratiePdf();
    }
}

backend/views/subscriber/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\Category;
use common\models\Subscriber;

/* @var $this yii\web\View */
/* @var $model app\models\Subscriber */
/* @var $form yii\widgets\ActiveForm */
/* @var $categories array */

$tshirtSizes = \common\models\Subscriber::getTshirtSizeOptions();

?>

<div class="subscriber-form">

    <?php $form = ActiveForm::begin(); ?>
	
    <?= $form->field($model, 'number')->textInput() ?>
    <?= $form->field($model, 'first_name')->textInput(['maxlength' => 255]) ?>   
    <?= $form->field($model, 'last_name')->textInput(['maxlength' => 255]) ?>
    <?= $form->field($model, 'pnc')->textInput() ?>
    <?= $form->field($model, 'year_of_birth')->textInput() ?>
    <?= $form->field($model, 'category_id')->dropDownList($categories, ['prompt' => 'Selectează']); ?>
    
    <?= $form->field($model, 'city')->textInput(['maxlength' => 255]) ?>
    <?= $form->field($model, 'gender')->dropDownList([ 'F' => 'F', 'M' => 'M', ], ['prompt' => 'Selectează']) ?>
    <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>
    <?= $form->field($model, 'phone')->textInput(['maxlength' => 20]) ?>
    <?= $form->field($model, 'team')->textInput(['maxlength' => 255]) ?>	    
    <?= $form->field($model, 'tshirt_size')->dropDownList($tshirtSizes, ['prompt'=>'Alege mărimea tricoului...']) ?>

	 <?= $form->field($model, 'amount_to_pay')->textInput() ?>
    <?= $form->field($model, 'payed')->dropDownList([Subscriber::PAYED => 'Da', Subscriber::NOT_PAYED => 'Nu', ], ['prompt' => 'Selectează']) ?>
	 <?= $form->field($model, 'amount_payed')->textInput() ?>
    <?= $form->field($model, 'payment_description')->textInput(['maxlength' => 255]) ?>
    <?= $form->field($model, 'payment_date')->textInput(['maxlength' => 255]) ?>
	
    <?= $form->field($model, 'email_sent')->dropDownList(['1' => 'Da', '0' => 'Nu', ], ['prompt' => 'Selectează']) ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/subscriber/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SubscriberSearch */
/* @var $form yii\widgets\ActiveForm */

$categories = \common\models\Category::getCategoriesListItems("MBR2019");

?>

<div class="subscriber-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>
    
    <?= $form->field($model, 'category_id')->dropDownList($categories, ['prompt' => 'Selectează']); ?>

    <?= $form->field($model, 'pnc') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>
    
    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/subscriber/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Subscriber */

$this->title = 'Adauga participant nou';
$this->params['breadcrumbs'][] = ['label' => 'Subscribers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="subscriber-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model, 'categories' => $categories
    ]) ?>

</div>

backend/views/subscriber/declaratie.php
<?php
use yii\helpers\Html;
use Da\QrCode\QrCode;

$qrCode = (new QrCode($subscriber->hash))
    ->setSize(100)
    ->setMargin(5)
    ->useForegroundColor(0, 0, 0);
?>

<div>
    <div>
        <img src="img/logo-mbr.png" alt="Mamut Bike Race" width="250" style="text-align: left; float: left"/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span style="margin-left: 50px;float:left">
            Numar concurs: <img src="img/numar_declaratie.png" alt="Mamut Bike Race" width="100"/>
        </span>
        <?php
        // or even as data:uri url
        echo '<img src="' . $qrCode->writeDataUri() . '" style="float:right; text-align:right">';
        ?>
    </div>
    <div>

        <h4>Cursa: <?= Html::encode($course->title) ?></h4>
        <h4>Categoria: <?= Html::encode($category->title) ?></h4>
    </div>
    <h3 style="text-align: center">DECLARAŢIE PE PROPRIE RĂSPUNDERE</h3>  <br />
    <p>Subsemnatul(a) <b><?= Html::encode($subscriber->first_name) ?> <?= Html::encode($subscriber->last_name) ?></b>, născut(ă) in anul <b><?= Html::encode($subscriber->year_of_birth) ?></b>,
        domiciliat(ă) în localitatea <b><?= Html::encode($subscriber->city) ?></b>, <b><?= Html::encode($subscriber->address) ?></b>, judeţul <b><?= Html::encode($subscriber->judet) ?></b>,
        identificat cu C.N.P. <b><?= Html::encode($subscriber->pnc) ?></b>, telefon de contact <b><?= Html::encode($subscriber->phone) ?></b>,
        în calitate de participant la competiţia de ciclism;
    </p>
    <p style="font-size: 12px">declar pe proprie răspundere că am citit toate informaţiile publicate pe site-ul competiţiei Mamut Bike Race (abreviată MBR2019),
        organizată în data de 14.09.2019 (sâmbătă), pe traseul stabilit în apropierea municipiului Alba Iulia, jud. Alba.
        Menţionez că sunt informat(ă) în legătură cu riscurile pe care le implică practicarea ciclismului în condiţiile deosebite
        pe care le presupune un asemenea eveniment sportiv, sunt de acord cu aceste condiţii şi, în cazul implicării mele într-un accident
        survenit în timpul concursului, îmi voi asuma întreaga răspundere pentru incidentul respectiv şi nu voi pretinde organizatorului
        nici un fel de daune pentru acesta. Menționez că sunt asigurat medical, în eventualitatea unui accident.
    </p>
   <p style="font-size: 12px">
       Precizez că nu îi voi trage pe organizatorii concursului la răspundere în cazul în care voi fi descalificat din compeţitie pentru nerespectarea regulamentului concursului
   </p>
    <p style="font-size: 12px">
        Pe propria mea răspundere, mai declar următoarele:
    </p>
    <p style="font-size: 12px">
        1. Datele de mai sus sunt corecte și exacte; <br/>
        2. Sunt clinic sănătos/sănătoasă şi nu sufăr de nicio afecţiune care să îmi pericliteze starea de sănătate în timpul desfăşurării evenimentului şi îmi asum întrega responsabilitate în ceea ce priveşte participarea mea la concursul de ciclism MBR2019; <br/>
        3. Sunt de acord să particip la concursul de mountain-bike MBR2019. Am citit, am luat la cunoştinţă şi am înţeles pe deplin Regulamentul de Participare publicat pe site-ul http://mamut.bicheru-cycling.ro/regulament, sunt de acord cu acesta și îl voi respecta în totalitate; <br/>
        4. Am echipamentul adecvat pentru participarea la această competiţie (cască de protecţie, echipament de protecţie, bicicletă în stare foarte bună de funcţionare etc.); <br/>
        5. M-am informat asupra tuturor detaliilor şi riscurilor concursului, pe care mi le asum în totalitate. Cunosc faptul că traseul nu este închis circulaţiei publice, putând apărea animale, vehicule sau alte persoane în afara concursului; <br/>
        6. Organizatorul şi reprezentanţii săi nu pot fi traşi la răspundere pentru niciun fel de rănire sau pierdere, oricare ar fi motivul acesteia. Înţeleg implicaţiile juridice ale participării la acest concurs şi îmi asum întreaga răspundere. <br/>
        7. Am înţeles că informaţiile cu caracter personal vor fi stocate de către organizator exclusiv în scopul organizării competiţiei sportive. Am înţeles că anumite date vor apărea pe liste publice (nume, prenume, localitate, categoria de vârstă, rezultat etc.); <br/>
        8. Mă consider capabil(ă) să termin această cursă *** <br/>
        *** Dacă suferiţi de vreo afecţiune medicală vă rugăm să aduceţi acest lucru la cunoştinţă organizatorului. Sugerăm ca, pentru a  participa la competiţii sportive, să consultaţi în prealabil medicul de familie şi să aveţi acordul acestuia. <br/>

    </p>
    <p>
        <span style="float: left; font-weight: bold;font-size: 12px">Data: ...................</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span style="float: right; font-weight: bold;font-size: 12px">Semnatura: ......................</span>
    </p>
</div>

backend/views/subscriber/paylist.php
<?php
/**
 * paylist.php
 *
 * @author      Claudiu Crisan
 * @copyright   eins+null GmbH & Co. KG
 * @date        23/05/2017
 * @encoding    UTF-8
 */
use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Subscriber;

/* @var $this yii\web\View */
/* @var $searchModel \backend\models\SubscriberSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Lista plătitori';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="subscriber-index">
    
    <h1><?= Html::encode($this->title) ?></h1>
    <?= Yii::$app->session->getFlash('success'); ?>
    
    <?= Html::beginForm(['subscriber/bulkpay'], 'post'); ?>
    <table cellpadding="3">
        <tr>
            <td>Suma:</td><td><?= Html::textInput('suma') ?></td>
            <td>Data platii:</td><td><?= Html::textInput('data', null, ['placeholder' => 'aaaa-ll-zz'])?></td>
            <td>Descriere plata:</td><td><?= Html::textInput('descriere')?></td>
            <td><?= Html::submitButton('Plateste', ['class' => 'btn btn-info',]); ?></td>
        </tr>
    </table>
    
    
    <?php
    
    $gridColumns = [
        ['class' => 'yii\grid\CheckboxColumn'],
        'id',
        [
            'attribute'=>'number',
            'label'=>'Numar'
        ],
        [
            'attribute' => 'event',
            'value' => 'event',
            'filter' => array('MBR2019' => "MBR2019"),
            'label' => 'Eveniment'
        ],
        [
            'attribute' => 'category',
            'value' => 'category',
            'label' => 'Categorie'
        ],
        [
            'attribute' => 'last_name',
            'value' => 'last_name',
            'label' => 'Nume'
        ],
        [
            'attribute' => 'first_name',
            'value' => 'first_name',
            'label' => 'Prenume'
        ],
        [
            'attribute' => 'payed',
            'format' => 'html',
            'contentOptions' => ['class' => 'centered'],
            'value' => function($data){
                return $data['payed'] === Subscriber::PAYED ? '<strong style="color:green;">DA</strong>' : '<strong style="color:red;">NU</strong>';
            },
            'filter' => array(Subscriber::PAYED => "Da", Subscriber::NOT_PAYED => "Nu"),
            'label' => 'Plătit?'
        ],
        [
            'attribute'=>'amount_payed',
            'label' => 'Suma platita'
        ],
        [
            'attribute'=>'payment_date',
            'label' => 'Data platii'
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'contentOptions' => ['style' => 'width:50px;'],
            'header' => 'Actions',
            'template' => '{update}',
        ]
        
    ];
    ?>
    
    <?php \yii\widgets\Pjax::begin(); ?>
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'summary' => "Total: {totalCount} înscriși",
        'emptyText' => "Nu am găsit rezultate",
        'tableOptions' => [
            'class' => 'table table-striped table-bordered'
        ],
        'columns' => $gridColumns
    ]);
    ?>
    <?php \yii\widgets\Pjax::end(); ?>
    
    <?= Html::endForm();?>
</div>

backend/views/subscriber/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Subscriber */
/* @var $categories array */

$this->title = 'Modifica date participant: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Subscribers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="subscriber-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model, 'categories' => $categories
    ]) ?>

</div>

backend/views/subscriber/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Subscriber */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Subscribers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="subscriber-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'category_id',
            'pnc',
            'first_name',
            'last_name',
            'year_of_birth',
            'gender',
            'email:email',
            'phone',
        ],
    ]) ?>

</div>